# Metrics reporting
metrics:
  reporters:
    - type: influxdb
      globalTags:
        env: production
      metricTemplates:
        services:
          pattern: com\.kickstarter\.services\.(?<service>[A-Za-z]+).*
          tagKeys: ["service"]
      groupGauges: true
      groupCounters: false
      sender:
        type: tcp
        host: localhost
        port: 90210
        timeout: 5000000 days # keep alive as long as possible


